version: "3"

services:
  # MongoDB container
  mongodb:
    image: mongo:latest
    container_name: mongodb_container_API_ETNA
    environment:
      MONGO_INITDB_ROOT_USERNAME: wawamatt
      MONGO_INITDB_ROOT_PASSWORD: wawamatt
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongodb_data:/data/db


  # Node.js API container
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_container_API_ETNA
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb+srv://wawamatt:wawamatt@api.5brmuyy.mongodb.net/API"
    ports:
      - "5000:5000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data: